server:
  port: 5011
  tomcat:
      max-connections: 1000
      max-threads: 1000

region:
  response:
    max: 1000
  datasource:
    uri: mongodb://192.168.1.12:27017/argo-region-pub
    database: argo-region-pub
    collection: regions
    max: 10000
    min: 20
  mq:
    maxThreads: 200
    maxCount: 1

spring:
  rabbitmq:
    port: 5672
    host: 192.168.1.12
    username: ARGO
    password: xq3askJWmegaewdkf;la3qdawef

logging:
  slf4j:
    enabled: true
  rabbitmq:
    enabled: true
    exchangeName: log
    declareExchange: true
  project:
    application: argo-region-pub